config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

  authenticated :user, ->(user) { user.is_admin? } do
    root to: "admin/dashboard#index", as: :admin_root
  end

  authenticated :user, ->(user) { user.is_candidate? } do
    root to: "questions#index", as: :candidate_root
  end

  root to: "questions#index"
  resources :questions, only: [ :index ]
  patch 'submit_answer/:user_id' => 'questions#submit_answer'

  scope module: 'admin', path: 'admin' do
    get 'dashboard' => 'dashboard#index', as: :admin_dashboard

    resources :users, except: [ :show ]
    resources :questions, except: [ :show ]
    resources :results, only: [ :index ]
    resources :tests, except: [ :show ]

    get 'users/import_users' => 'users#import', as: :user_import
    post 'users/import_users' => 'users#bulk_upload', as: :user_bulk_upload
    post 'users/send_reminder_mail' => 'users#send_reminder_mail', as: :send_reminder_mail
    post 'users/send_selection_mail' => 'users#send_selection_mail', as: :send_selection_mail
    post 'users/send_rejection_mail' => 'users#send_rejection_mail', as: :send_rejection_mail

    get 'questions/import_questions' => 'questions#import', as: :question_import
    post 'questions/import_questions' => 'questions#bulk_upload', as: :question_bulk_upload
  end
end

app/models/question.rb
class Question < ApplicationRecord
  def self.import(file)
    data = Roo::Excelx.new(file.tempfile)
    headers = data.row(1)

    data.each_with_index do |row, idx|
      next if idx == 0

      question_data = Hash[[headers, row].transpose]
      question_data = question_data.map { |k, v| [k ? (k.class == "String" ? k.strip : k) : k, v ? (v.class == "String" ? v.strip : v) : v] }.to_h

      Question.create(question_data)
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :set_question, only: [ :edit, :update, :destroy ]

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to "/admin/questions", notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to "/admin/questions", notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to "/admin/questions", notice: 'Question was successfully destroyed.' }
    end
  end

  def import
  end

  def bulk_upload
    Question.import(params[:file])

    respond_to do |format|
      format.html { redirect_to "/admin/questions", notice: 'Question was successfully uploaded.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question_text, :question_type, :options, :correct_answer, :tag)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  protect_from_forgery :except => [:submit_answer]

  def index
    @questions = []

    @test = Result.get_test_result(current_user.id, current_user.current_sign_in_at)
    tags = JSON.parse Test.first.tags
    @test_config = Test.first

    tags.each do |tag|
      @questions += Question.where(tag: tag["question_tag"]).limit(tag["count"]).order("RANDOM()")
    end
  end

  def submit_answer
    Result.where(user_id: current_user.id).update({ marks_get: params[:correct_answers], total_marks: params[:total_questions], percentage: params[:percentage] })
    User.where(id: current_user.id).update(took_test: true)
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with(model: question, local: true, class: "forms-sample") do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li style="list-style-type: none; margin-left: -2rem;">
            <span class="badge badge-sm bg-gradient-danger"><%= message %></span>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :question_text %>
    <%= f.text_field :question_text, class: "form-control", placeholder: "Question Text", required: true %>
  </div>
  
  <div class="form-group">
    <%= f.label :question_type %>
    <%= f.select :question_type, options_for_select({ "Choice" => "radiogroup" }, question.question_type), { prompt: "Select Type" }, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :options %>
    <%= f.text_field :options, class: "form-control", placeholder: "Question Options", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :correct_answer %>
    <%= f.text_field :correct_answer, class: "form-control", placeholder: "Correct Answer", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :tag %>
    <%= f.select :tag, options_for_select({ "Attention to Details" => "attention_to_details", "Critical Thinking" => "critical_thinking", "Numerical Reasoning" => "numerical_reasoning", "Verbal Reasoning" => "verbal_reasoning" }, question.tag), { prompt: "Select Tag" }, { class: "form-control" } %>
  </div>

  <%= f.submit class: "btn btn-primary mr-2" %>
  <%= link_to "Cancel", "/admin/questions", class: "btn btn-light" %>
<% end %>

app/views/admin/questions/edit.html.erb
<div class="content-wrapper">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Edit Question</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <%= render 'form', question: @question %>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/import.html.erb
<div class="content-wrapper">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Import Questions</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <%= form_with url: question_bulk_upload_path, local: true, class: "forms-sample" do |form| %>
          <div class="form-group">
            <label>File upload</label>
            <%= form.file_field :file, class: "file-upload-default", accept: ".xlsx", required: true %>

            <div class="input-group col-xs-12">
              <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Excel File">
              <span class="input-group-append">
                <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
              </span>
            </div>
          </div>

          <%= form.submit "Import", id:"action", class: "btn btn-primary mr-2" %>
          <%= link_to "Cancel", "/admin/questions", class: "btn btn-light" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/index.html.erb
<div class="content-wrapper">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <!--<div class ="col-md-12" align="right">
          <%#= link_to new_question_path, :class => "btn btn-success" do %>
            <i class="ti-plus custom-icon-text"></i>
            Create Question
          <%# end %>
        </div>-->

        <h4 class="card-title">Questions</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <div class="table-responsive">
          <table class="display expandable-table" style="width:100%" id="questions-datatable">
            <thead>
              <tr>
                <th>Question</th>
                <th>Options</th>
                <th>Correct Answer</th>
                <th>Tag</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              <% @questions.each do |question| %>
                <tr>
                  <td><%= trim_text(question.question_text) %></td>
                  <td><%= trim_text(question.options) %></td>
                  <td><%= trim_text(question.correct_answer) %></td>
                  <td>
                    <% class_name = (question.tag == "attention_to_details") ? "bg-warning" : ((question.tag == "critical_thinking") ? "bg-danger" : ((question.tag == "numerical_reasoning") ? "bg-success" : "bg-info")) %>
                    <span class="badge <%= class_name %> custom-badge"><%= question.tag.humanize %></span>
                  </td>
                  <td>
                    <%= link_to edit_question_path(question), class: "btn btn-default custom-btn" do %>
                      <i class="mdi mdi-pencil custom-icon"></i>
                    <% end %>
                    <%= link_to question, method: :delete, class: "btn btn-default custom-btn" do %>
                      <i class="mdi mdi-delete custom-icon"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/new.html.erb
<div class="content-wrapper">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Create Question</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <%= render 'form', question: @question %>
      </div>
    </div>
  </div>
</div>