config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

  authenticated :user, ->(user) { user.is_admin? } do
    root to: "admin/dashboard#index", as: :admin_root
  end

  authenticated :user, ->(user) { user.is_candidate? } do
    root to: "questions#index", as: :candidate_root
  end

  root to: "questions#index"
  resources :questions, only: [ :index ]
  patch 'submit_answer/:user_id' => 'questions#submit_answer'

  scope module: 'admin', path: 'admin' do
    get 'dashboard' => 'dashboard#index', as: :admin_dashboard

    resources :users, except: [ :show ]
    resources :questions, except: [ :show ]
    resources :results, only: [ :index ]
    resources :tests, except: [ :show ]

    get 'users/import_users' => 'users#import', as: :user_import
    post 'users/import_users' => 'users#bulk_upload', as: :user_bulk_upload
    post 'users/send_reminder_mail' => 'users#send_reminder_mail', as: :send_reminder_mail
    post 'users/send_selection_mail' => 'users#send_selection_mail', as: :send_selection_mail
    post 'users/send_rejection_mail' => 'users#send_rejection_mail', as: :send_rejection_mail

    get 'questions/import_questions' => 'questions#import', as: :question_import
    post 'questions/import_questions' => 'questions#bulk_upload', as: :question_bulk_upload
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable

  after_save :change_user_status

  has_many :results

  scope :test_sent_overall, -> { where(user_type: "candidate") }
  scope :test_taken_overall, -> { where(user_type: "candidate", took_test: true) }
  scope :test_not_taken_overall, -> { where(user_type: "candidate", took_test: false) }
  scope :test_sent_today, -> { where(user_type: "candidate", created_at: Date.today.at_beginning_of_day... Date.today.at_end_of_day) }
  scope :test_taken_today, -> { where(user_type: "candidate", took_test: true, created_at: Date.today.at_beginning_of_day... Date.today.at_end_of_day) }
  scope :above_benchmark, -> { User.includes(:results).where(user_type: "candidate", took_test: true, "results.percentage": 40..Float::INFINITY, "results.updated_at": Date.today.at_beginning_of_day... Date.today.at_end_of_day) }

  def self.import(file)
    data = Roo::Excelx.new(file.tempfile)
    headers = data.row(1)

    data.each_with_index do |row, idx|
      next if idx == 0

      user_data = Hash[[headers, row].transpose]
      user_data = user_data.map { |k, v| [k ? (k.class == "String" ? k.strip : k) : k, v ? (v.class == "String" ? v.strip : v) : v] }.to_h
      user_data.merge!(password: self.get_random_password)

      User.create(user_data)

      mail_data = ({
        name: user_data["name"],
        email: user_data["email"],
        password: user_data[:password],
        test_link: "https://hiring.spritle.com"
      }).to_json

      UserMailer.send_registeration_mail(mail_data).deliver_now!
    end
  end

  def self.get_random_password
    string = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
    return (0...10).map { string[rand(string.length)] }.join
  end

  def is_admin?
    self.user_type == "admin"
  end

  def is_candidate?
    self.user_type == "candidate"
  end

  private
    def change_user_status
      if self.took_test == true
        self.update_column(:status, "test_taken")
      else
        Result.where(user_id: self.id).destroy_all
      end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update, :destroy ]
  before_action :set_search_params, only: [ :index ]
  before_action :set_random_password, only: [ :new, :create ]

  def index
    @users = get_user_data

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_user_params)

    mail_data = ({
      name: create_user_params[:name],
      email: create_user_params[:email],
      password: create_user_params[:password],
      test_link: "https://hiring.spritle.com"
    }).to_json

    respond_to do |format|
      if @user.save
        UserMailer.send_registeration_mail(mail_data).deliver_now!

        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(update_user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy

    Result.where(user_id: @user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
    end
  end

  def import
  end

  def bulk_upload
    User.import(params[:file])
    redirect_to users_path
  end

  def send_reminder_mail
    params[:user_ids].each do |user_id|
      user = User.where(id: user_id, status: "test_not_taken")
      UserMailer.send_reminder_mail(user[0]).deliver_now! if user.present?

      user.update(reminder_sent: true)
    end

    render :json => { :status => "ok", :message => "Success!" }
  end

  def send_selection_mail
    params[:user_ids].each do |user_id|
      user = User.includes(:results).where(id: user_id, status: "test_taken").where({ results: { percentage: 40..Float::INFINITY }})

      if user.present? && user.length > 0
        UserMailer.send_selection_mail(user[0]).deliver_now!
  
        user.update(selection_sent: true)
      end
    end

    render :json => { :status => "ok", :message => "Success!" }
  end

  def send_rejection_mail
    params[:user_ids].each do |user_id|
      user = User.includes(:results).where(id: user_id, status: "test_taken").where({ results: { percentage: -Float::INFINITY..39 }})

      if user.present? && user.length > 0
        UserMailer.send_rejection_mail(user[0]).deliver_now!
  
        user.update(rejection_sent: true)
      end
    end

    render :json => { :status => "ok", :message => "Success!" }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def create_user_params
      params.require(:user).permit(:name, :email, :mobile, :password)
    end

    def update_user_params
      params.require(:user).permit(:name, :email, :mobile, :status, :took_test)
    end

    def set_search_params
      @date_from = (params[:date_from].present?) ? params[:date_from] : ""
      @date_to = (params[:date_to].present?) ? params[:date_to] : ((params[:date_from].present?) ? params[:date_from] : "")
      @status = params[:status].present? ? (params[:status].slice(-1) == "]" ? (JSON.parse params[:status]) : params[:status]) : ""
      @percentage = params[:percentage].present? ? params[:percentage] : ""
      @above_40 = params[:above_40].present? ? params[:above_40] : ""
    end

    def set_random_password
      @random_password = User.get_random_password
    end

    def get_user_data
      condition = {
        user_type: "candidate",
        created_at: (@date_from != "" && @date_to != "" ) ? (@date_from.to_date.at_beginning_of_day... @date_to.to_date.at_end_of_day) : "",
        status: (@status != "") ? @status : "",
        results: {
          percentage: (@percentage == "above") ? 40..Float::INFINITY : ((@percentage == "below") ? -Float::INFINITY..39 : "")
        }
      }

      if @above_40 != ""
        condition[:results][:updated_at] = condition[:created_at]
        condition[:created_at] = ""
      end

      condition.delete(:created_at) if condition[:created_at] == ""
      condition.delete(:status) if condition[:status] == ""
      condition.delete(:results) if condition[:results][:percentage] == ""

      return User.includes(:results).where(condition).order(created_at: :desc)
    end
end

app/views/admin/users/_filters.html.erb
<div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
  <ul class="navbar-nav navbar-nav-right mr-4">
    <li class="nav-item dropdown" align="right">
      <%= link_to new_user_path, :class => "nav-link", title: "Add New Candidate" do %>
        <i class="mdi mdi-account-plus mx-0 custom-filter"></i>
      <% end %>
    </li>
  </ul>

  <% if @users.length > 0 %>
    <ul class="navbar-nav navbar-nav-right mr-4">
      <li class="nav-item dropdown" align="right">
        <%= link_to users_path(format: "xlsx", params: request.params), :class => "nav-link", title: "Export" do %>
          <i class="mdi mdi-file-export mx-0 custom-filter"></i>
        <% end %>
      </li>
    </ul>
  <% end %>

  <ul class="navbar-nav navbar-nav-right mr-4" id="send-mail">
    <li class="nav-item dropdown" align="right">
      <a class="nav-link" id="emailDropdown" href="#" data-toggle="dropdown" title="Mail">
        <i class="mdi mdi-email mx-0 custom-filter"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="emailDropdown">
        <%= link_to "#", class: "dropdown-item preview-item", id: "send-reminder-mail", title: "Send Reminder Mail" do %>
          <div class="preview-thumbnail">
            <div class="preview-icon bg-info">
              <i class="ti-email mx-0"></i>
            </div>
          </div>
          <div class="preview-item-content custom-preview-item-content">
            <h6 class="preview-subject font-weight-normal">Reminder Mail</h6>
          </div>
        <% end %>
        <%= link_to "#", class: "dropdown-item preview-item", id: "send-selection-mail", title: "Send Selection Mail" do %>
          <div class="preview-thumbnail">
            <div class="preview-icon bg-success">
              <i class="ti-email mx-0"></i>
            </div>
          </div>
          <div class="preview-item-content custom-preview-item-content">
            <h6 class="preview-subject font-weight-normal">Selection Mail</h6>
          </div>
        <% end %>
        <%= link_to "#", class: "dropdown-item preview-item", id: "send-rejection-mail", title: "Send Rejection Mail" do %>
          <div class="preview-thumbnail">
            <div class="preview-icon bg-danger">
              <i class="ti-email mx-0"></i>
            </div>
          </div>
          <div class="preview-item-content custom-preview-item-content">
            <h6 class="preview-subject font-weight-normal">Rejection Mail</h6>
          </div>
        <% end %>
      </div>
    </li>
  </ul>

  <ul class="navbar-nav navbar-nav-right mr-4">
    <li class="nav-item dropdown" align="right">
      <a class="nav-link" id="filterDropdown" href="#" data-toggle="dropdown" title="Filter">
        <i class="mdi mdi-filter mx-0 custom-filter"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list custom-dropdown-menu" aria-labelledby="filterDropdown">
        <div class ="col-md-12">
          <%= form_tag(users_path, method: "get", class: "forms-sample") do %>
            <div class="form-group">
              <label>From</label>
              <%= date_field_tag "date_from", @date_from, class: 'form-control' %>
            </div>
            <div class="form-group">
              <label>To</label>
              <%= date_field_tag "date_to", @date_to, class: 'form-control' %>
            </div>
            <div class="form-group">
              <label>Status</label>
              <%= select_tag "status", options_for_select({ "Test Taken" => "test_taken", "Test Sent" => "test_sent", "Test Not Taken" => "test_not_taken" }, @status), { prompt: "Select Status", class: "form-control" } %>
            </div>
            <div class="form-group">
              <label>Percentage</label>
              <%= select_tag "percentage", options_for_select({ "Above 40%" => "above", "Below 40%" => "below" }, @percentage), { prompt: "Select Percentage", class: "form-control" } %>
            </div>
            <%= submit_tag "Apply", class: "btn btn-block btn-primary mr-2" %>
          <% end %>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/admin/users/_form.html.erb
<%= form_with(model: user, local: true, class: "forms-sample") do |f| %>

  <% if action_name == "new" || action_name == "create" %>
    <%= f.hidden_field :password, value: @random_password %>
  <% end %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li style="list-style-type: none; margin-left: -1rem;">
            <span class="badge badge-sm bg-gradient-danger"><%= message %></span>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :mobile %>
    <%= f.text_field :mobile, class: "form-control", placeholder: "Mobile" %>
  </div>

  <% if action_name == "edit" || action_name == "update" %>
    <div class="form-group">
      <%= f.label :status %>
      <%= f.select :status, options_for_select({ "Test Taken" => "test_taken", "Test Sent" => "test_sent", "Test Not Taken" => "test_not_taken" }, user.status), { prompt: "Select Status" }, { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= f.label :took_test %>?
      <%= f.select :took_test, options_for_select({ "Yes" => true, "No" => false }, user.took_test), {}, { class: "form-control" } %>
    </div>

    <%= f.submit "Update Candidate", class: "btn btn-primary mr-2" %>
  <% else %>
    <%= f.submit "Create & Send Test", class: "btn btn-primary mr-2" %>
  <% end %>
  <%= link_to "Cancel", users_path, class: "btn btn-light" %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="content-wrapper">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Edit Candidate</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/import.html.erb
<div class="content-wrapper">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Import Candidates</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <%= form_with url: user_bulk_upload_path, local: true, class: "forms-sample" do |form| %>
          <div class="form-group">
            <label>File upload</label>
            <%= form.file_field :file, class: "file-upload-default", accept: ".xlsx", required: true %>

            <div class="input-group col-xs-12">
              <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Excel File">
              <span class="input-group-append">
                <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
              </span>
            </div>
          </div>

          <%= form.submit "Import & Sent Test", id:"action", class: "btn btn-primary mr-2" %>
          <%= link_to "Cancel", users_path, class: "btn btn-light" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="content-wrapper">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <%= render "filters" %>

        <h4 class="card-title">Candidates</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <div class="table-responsive">
          <table class="display expandable-table" style="width:100%" id="users-datatable">
            <thead>
              <tr>
                <th width="5%" class="text-center"><input type="checkbox" id="checkAll" ></th>
                <th width="15%">Name</th>
                <th width="20%">Email</th>
                <th width="15%" class="text-center">Status</th>
                <th width="15%" class="text-center">Test Taken Date</th>
                <th width="15%" class="text-center">Percentage</th>
                <th width="15%" class="text-center">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td class="text-center"><input type="checkbox" class="checkItem" value="<%= user.id %>"></td>
                  <td>
                    <%= user.name %>
                    <% if user.reminder_sent == true %>
                      <i class="mdi mdi-check-circle custom-icon custom-blue-tick-icon" title="Reminder Mail Sent"></i>
                    <% end %>
                    <% if user.selection_sent == true %>
                      <i class="mdi mdi-check-circle custom-icon custom-green-tick-icon" title="Selection Mail Sent"></i>
                    <% end %>
                    <% if user.rejection_sent == true %>
                      <i class="mdi mdi-check-circle custom-icon custom-red-tick-icon" title="Rejection Mail Sent"></i>
                    <% end %>
                  </td>
                  <td><%= user.email %></td>
                  <td class="text-center">
                    <% class_name = (user.status == "test_sent") ? "badge-info" : ((user.status == "test_taken") ? "badge-success" : "badge-danger") %>
                    <span class="badge <%= class_name %> custom-badge"><%= user.status.humanize %></span>
                  </td>
                  <td class="text-center"><%= user.results.present? ? "#{get_date_format(user.results.first.updated_at)}" : "-" %></td>
                  <td class="text-center"><%= user.results.present? ? "#{user.results.first.percentage.to_i}%" : "-" %></td>
                  <td class="text-center">
                    <%= link_to edit_user_path(user), class: "btn btn-default custom-btn" do %>
                      <i class="mdi mdi-pencil custom-icon"></i>
                    <% end %>
                    <%= link_to user, method: :delete, class: "btn btn-default custom-btn" do %>
                      <i class="mdi mdi-delete custom-icon"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="content-wrapper">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Create Candidate</h4>
        <!--<p class="card-description">
          Add class <code>.table-hover</code>
        </p>-->

        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>