config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

  authenticated :user, ->(user) { user.is_admin? } do
    root to: "admin/dashboard#index", as: :admin_root
  end

  authenticated :user, ->(user) { user.is_candidate? } do
    root to: "questions#index", as: :candidate_root
  end

  root to: "questions#index"
  resources :questions, only: [ :index ]
  patch 'submit_answer/:user_id' => 'questions#submit_answer'

  scope module: 'admin', path: 'admin' do
    get 'dashboard' => 'dashboard#index', as: :admin_dashboard

    resources :users, except: [ :show ]
    resources :questions, except: [ :show ]
    resources :results, only: [ :index ]
    resources :tests, except: [ :show ]

    get 'users/import_users' => 'users#import', as: :user_import
    post 'users/import_users' => 'users#bulk_upload', as: :user_bulk_upload
    post 'users/send_reminder_mail' => 'users#send_reminder_mail', as: :send_reminder_mail
    post 'users/send_selection_mail' => 'users#send_selection_mail', as: :send_selection_mail
    post 'users/send_rejection_mail' => 'users#send_rejection_mail', as: :send_rejection_mail

    get 'questions/import_questions' => 'questions#import', as: :question_import
    post 'questions/import_questions' => 'questions#bulk_upload', as: :question_bulk_upload
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i> by <a href="https://spritle.com" target="blank">Spritle</a></span>
  </div>
</footer>

app/views/layouts/_side_nav_bar.html.erb
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to admin_dashboard_path, class: "nav-link" do %>
        <i class="mdi mdi-view-dashboard menu-icon"></i>
        <span class="menu-title">Dashboard</span>
      <% end %>
    </li>

    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#candidates" aria-expanded="false" aria-controls="candidates">
        <i class="mdi mdi-account-multiple menu-icon"></i>
        <span class="menu-title">Candidates</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="candidates">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <%= link_to "Candidates Directory", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Import Candidates", user_import_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </li>

    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#questions" aria-expanded="false" aria-controls="questions">
        <i class="mdi mdi-help-circle menu-icon"></i>
        <span class="menu-title">Questions</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="questions">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <%= link_to "List Questions", "/admin/questions", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Import Questions", question_import_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </li>

    <li class="nav-item">
      <%= link_to tests_path, class: "nav-link" do %>
        <i class="mdi mdi-receipt menu-icon"></i>
        <span class="menu-title">Tests</span>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/_toast_flash_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>', '', {
        "closeButton": true,
        "positionClass": "toast-top-right",
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "progressBar": true,
        "hideMethod": "fadeOut"
      });
    <% end %>
  </script>
<% end %>

app/views/layouts/_top_nav_bar.html.erb
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo mr-5" href="/">
      <%= image_tag ("/assets/spritle_logo.png"), class: "mr-2", alt: "logo" %>
    </a>
    <a class="navbar-brand brand-logo-mini" href="/">
      <%= image_tag ("/assets/favicon.ico"), alt: "logo" %>
    </a>
  </div>

  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <% if current_user.is_admin? %>
      <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
        <span class="icon-menu"></span>
      </button>

      <!--<ul class="navbar-nav mr-lg-2">
        <li class="nav-item nav-search d-none d-lg-block">
          <div class="input-group">
            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
              <span class="input-group-text" id="search">
                <i class="icon-search"></i>
              </span>
            </div>
            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
          </div>
        </li>
      </ul>-->
    <% end %>

    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
          <%= user_gravatar current_user %>
        </a>

        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
          <!--<a class="dropdown-item">
            <i class="ti-settings text-primary"></i>
            Settings
          </a>-->
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item", id: "logout" do %>
            <i class="ti-power-off text-primary"></i>
            Logout
          <% end %>
        </div>
      </li>
    </ul>

    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="icon-menu"></span>
    </button>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Spritle - Online Test</title>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/layouts/toast_flash_messages" %>

    <div class="container-scroller">
      <% if current_user == nil %>
        <%= yield %>
      <% elsif current_user != nil && current_user.is_admin? %>
        <%= render "/layouts/top_nav_bar" %>

        <div class="container-fluid page-body-wrapper">
          <%= render "/layouts/side_nav_bar" %>

          <div class="main-panel">
            <%= yield %>

            <%= render '/layouts/footer'%>
          </div>
        </div>
      <% elsif current_user != nil && current_user.is_candidate? %>
        <%= render "/layouts/top_nav_bar" %>

        <div class="container-fluid page-body-wrapper">
          <%= yield %>
        </div>
      <% end %>
    </div>
  </body>
</html>